[book]
authors = ["Mi Guoliang"]
language = "en"
multilingual = false
src = "src"
title = "A Silent Coder"
description = "Silence is gold."
git-repository-url = "https://github.com/miguoliang"
google-analytics = "G-2M7MGN5YXZ"
