baseURL = 'https://miguoliang.com/'
languageCode = 'en-us'
title = "Mi's Blog"
theme = 'nostyleplease'

[params]
author = "Mi Guoliang"
keywords = "chinese,male,son,husband,father,coder,manager"
description = "Mi Guoliang's personal website"

[params.googleTagManager]
id = "G-3XTC5Q3D4Y"
